### ISSUE TITLE
fusion-inspector: Genome version: 2.7.1a is INCOMPATIBLE with running STAR version: 2.7.0f

### ISSUE THREAD

**Issue by MaxUlysse** [nf-core/rnafusion#120]
command line:
```
nextflow run nf-core/rnafusion -r dev -profile munin --reads '/data1/references/rnafusion/1.1.0/reads_{1,2}.fq.gz' --arriba --fusioncatcher --pizzly --squid --arriba_vis --fusion_inspector -resume
```
container:
```
/data1/containers/nfcore-rnafusion-fusion-inspector_1.3.1-star2.7.0f.img
```

error:
```
Error executing process > 'fusion_inspector (reads)'

Caused by:
  Process `fusion_inspector (reads)` terminated with an error exit status (1)

Command executed:

  FusionInspector \
      --fusions reads_fusion_list.tsv \
      --genome_lib ctat_genome_lib_build_dir \
      --left_fq reads_1.fq.gz \
      --right_fq reads_2.fq.gz \
      --CPU 12 \
      --out_dir . \
      --out_prefix finspector \

Command exit status:
  1

Command output:
  Running: /opt/conda/envs/nf-core-rnafusion-fusion-inspector_1.3.1-star2.7.0f/share/fusion-inspector-1.3.1-1/util/fusion_pair_to_mini_genome_join.pl --fusions reads_fusion_list.tsv --gtf ctat_genome_lib_build_dir/ref_annot.gtf --genome_fa ctat_genome_lib_build_dir/ref_genome.fa --shrink_introns --max_intron_length 1000  --out_prefix finspector
  Running: touch chckpts_dir/fusion_contigs.ok
  Running: cp finspector.fa fi_workdir/finspector.fa
  Running: touch chckpts_dir/cp_contigs_file_workdir
  Running: cp finspector.gtf fi_workdir/finspector.gtf
  Running: touch chckpts_dir/cp_gtf_file_workdir.ok
  Running: /opt/conda/envs/nf-core-rnafusion-fusion-inspector_1.3.1-star2.7.0f/share/fusion-inspector-1.3.1-1/util/fasta_and_gtf_to_cytoband.pl finspector.fa finspector.gtf > cytoBand.txt
  Running: touch chckpts_dir/cytoband.ok
  Running: /opt/conda/envs/nf-core-rnafusion-fusion-inspector_1.3.1-star2.7.0f/share/fusion-inspector-1.3.1-1/util/gtf_gene_to_bed.pl finspector.gtf > finspector.bed
  Running: touch chckpts_dir/merged_contig_gtf_to_bed.ok
  Running: sort -k1,1 -k2,2n finspector.bed > finspector.bed.sorted.bed
  Running: touch chckpts_dir/finspector.bed.bedsort.ok
  Running: bgzip -f finspector.bed.sorted.bed
  Running: touch chckpts_dir/finspector.bed.bgzip.ok
  Running: tabix -p bed finspector.bed.sorted.bed.gz
  Running: touch chckpts_dir/finspector.bed.tabix.ok
  Running: samtools faidx finspector.fa
  Running: touch chckpts_dir/merged_contig_fai.ok
  Running: /opt/conda/envs/nf-core-rnafusion-fusion-inspector_1.3.1-star2.7.0f/share/fusion-inspector-1.3.1-1/util/run_FI_STAR.pl --genome ctat_genome_lib_build_dir/ref_genome.fa --patch fi_workdir/finspector.fa -G fi_workdir/finspector.gtf --CPU 12 --out_prefix finspector.star --out_dir fi_workdir --reads "reads_1.fq.gz reads_2.fq.gz"
  Apr 29 11:27:38 ..... started STAR run
  Apr 29 11:27:38 ..... loading genome

Command error:
  Error, chr discrepancy in gtf info for chrY	HAVANA	exon	1212556	1212649	.	-	.	gene_id "CRLF2^ENSG00000205755.12_PAR_Y"; transcript_id "ENST00000400841.8_PAR_Y"; gene_type "protein_coding"; gene_name "CRLF2"; transcript_type "protein_coding"; transcript_name "CRLF2-203"; exon_number 1; exon_id "ENSE00003755992.2"; level 2; protein_id "ENSP00000383641.3"; transcript_support_level "1"; hgnc_id "HGNC:14281"; tag "basic"; tag "MANE_Select"; tag "appris_principal_1"; tag "CCDS"; tag "PAR"; ccdsid "CCDS75945.1"; havana_gene "OTTHUMG00000067432.3"; havana_transcript "OTTHUMT00000144413.3"; FI_gene_label "CRLF2^ENSG00000205755.12_PAR_Y"; orig_coord_info "chrY,1212556,1212649,-";
  Error, chr discrepancy in gtf info for chrY	HAVANA	exon	1208806	1208908	.	-	.	gene_id "CRLF2^ENSG00000205755.12_PAR_Y"; transcript_id "ENST00000400841.8_PAR_Y"; gene_type "protein_coding"; gene_name "CRLF2"; transcript_type "protein_coding"; transcript_name "CRLF2-203"; exon_number 2; exon_id "ENSE00001725348.1"; level 2; protein_id "ENSP00000383641.3"; transcript_support_level "1"; hgnc_id "HGNC:14281"; tag "basic"; tag "MANE_Select"; tag "appris_principal_1"; tag "CCDS"; tag "PAR"; ccdsid "CCDS75945.1"; havana_gene "OTTHUMG00000067432.3"; havana_transcript "OTTHUMT00000144413.3"; FI_gene_label "CRLF2^ENSG00000205755.12_PAR_Y"; orig_coord_info "chrY,1208806,1208908,-";
  Error, chr discrepancy in gtf info for chrY	HAVANA	exon	1206433	1206599	.	-	.	gene_id "CRLF2^ENSG00000205755.12_PAR_Y"; transcript_id "ENST00000400841.8_PAR_Y"; gene_type "protein_coding"; gene_name "CRLF2"; transcript_type "protein_coding"; transcript_name "CRLF2-203"; exon_number 3; exon_id "ENSE00003755862.1"; level 2; protein_id "ENSP00000383641.3"; transcript_support_level "1"; hgnc_id "HGNC:14281"; tag "basic"; tag "MANE_Select"; tag "appris_principal_1"; tag "CCDS"; tag "PAR"; ccdsid "CCDS75945.1"; havana_gene "OTTHUMG00000067432.3"; havana_transcript "OTTHUMT00000144413.3"; FI_gene_label "CRLF2^ENSG00000205755.12_PAR_Y"; orig_coord_info "chrY,1206433,1206599,-";
  Error, chr discrepancy in gtf info for chrY	HAVANA	exon	1202402	1202535	.	-	.	gene_id "CRLF2^ENSG00000205755.12_PAR_Y"; transcript_id "ENST00000400841.8_PAR_Y"; gene_type "protein_coding"; gene_name "CRLF2"; transcript_type "protein_coding"; transcript_name "CRLF2-203"; exon_number 4; exon_id "ENSE00003756004.1"; level 2; protein_id "ENSP00000383641.3"; transcript_support_level "1"; hgnc_id "HGNC:14281"; tag "basic"; tag "MANE_Select"; tag "appris_principal_1"; tag "CCDS"; tag "PAR"; ccdsid "CCDS75945.1"; havana_gene "OTTHUMG00000067432.3"; havana_transcript "OTTHUMT00000144413.3"; FI_gene_label "CRLF2^ENSG00000205755.12_PAR_Y"; orig_coord_info "chrY,1202402,1202535,-";
  Error, chr discrepancy in gtf info for chrY	HAVANA	exon	1198562	1198724	.	-	.	gene_id "CRLF2^ENSG00000205755.12_PAR_Y"; transcript_id "ENST00000400841.8_PAR_Y"; gene_type "protein_coding"; gene_name "CRLF2"; transcript_type "protein_coding"; transcript_name "CRLF2-203"; exon_number 5; exon_id "ENSE00001752466.1"; level 2; protein_id "ENSP00000383641.3"; transcript_support_level "1"; hgnc_id "HGNC:14281"; tag "basic"; tag "MANE_Select"; tag "appris_principal_1"; tag "CCDS"; tag "PAR"; ccdsid "CCDS75945.1"; havana_gene "OTTHUMG00000067432.3"; havana_transcript "OTTHUMT00000144413.3"; FI_gene_label "CRLF2^ENSG00000205755.12_PAR_Y"; orig_coord_info "chrY,1198562,1198724,-";
  Error, chr discrepancy in gtf info for chrY	HAVANA	exon	1196780	1196900	.	-	.	gene_id "CRLF2^ENSG00000205755.12_PAR_Y"; transcript_id "ENST00000400841.8_PAR_Y"; gene_type "protein_coding"; gene_name "CRLF2"; transcript_type "protein_coding"; transcript_name "CRLF2-203"; exon_number 6; exon_id "ENSE00003755355.1"; level 2; protein_id "ENSP00000383641.3"; transcript_support_level "1"; hgnc_id "HGNC:14281"; tag "basic"; tag "MANE_Select"; tag "appris_principal_1"; tag "CCDS"; tag "PAR"; ccdsid "CCDS75945.1"; havana_gene "OTTHUMG00000067432.3"; havana_transcript "OTTHUMT00000144413.3"; FI_gene_label "CRLF2^ENSG00000205755.12_PAR_Y"; orig_coord_info "chrY,1196780,1196900,-";
  Error, chr discrepancy in gtf info for chrY	HAVANA	exon	1193218	1193302	.	-	.	gene_id "CRLF2^ENSG00000205755.12_PAR_Y"; transcript_id "ENST00000400841.8_PAR_Y"; gene_type "protein_coding"; gene_name "CRLF2"; transcript_type "protein_coding"; transcript_name "CRLF2-203"; exon_number 7; exon_id "ENSE00003746279.1"; level 2; protein_id "ENSP00000383641.3"; transcript_support_level "1"; hgnc_id "HGNC:14281"; tag "basic"; tag "MANE_Select"; tag "appris_principal_1"; tag "CCDS"; tag "PAR"; ccdsid "CCDS75945.1"; havana_gene "OTTHUMG00000067432.3"; havana_transcript "OTTHUMT00000144413.3"; FI_gene_label "CRLF2^ENSG00000205755.12_PAR_Y"; orig_coord_info "chrY,1193218,1193302,-";
  Error, chr discrepancy in gtf info for chrY	HAVANA	exon	1190490	1191160	.	-	.	gene_id "CRLF2^ENSG00000205755.12_PAR_Y"; transcript_id "ENST00000400841.8_PAR_Y"; gene_type "protein_coding"; gene_name "CRLF2"; transcript_type "protein_coding"; transcript_name "CRLF2-203"; exon_number 8; exon_id "ENSE00003758390.1"; level 2; protein_id "ENSP00000383641.3"; transcript_support_level "1"; hgnc_id "HGNC:14281"; tag "basic"; tag "MANE_Select"; tag "appris_principal_1"; tag "CCDS"; tag "PAR"; ccdsid "CCDS75945.1"; havana_gene "OTTHUMG00000067432.3"; havana_transcript "OTTHUMT00000144413.3"; FI_gene_label "CRLF2^ENSG00000205755.12_PAR_Y"; orig_coord_info "chrY,1190490,1191160,-";
  Error, chr discrepancy in gtf info for chrY	HAVANA	exon	1212556	1212723	.	-	.	gene_id "CRLF2^ENSG00000205755.12_PAR_Y"; transcript_id "ENST00000467626.6_PAR_Y"; gene_type "protein_coding"; gene_name "CRLF2"; transcript_type "nonsense_mediated_decay"; transcript_name "CRLF2-204"; exon_number 1; exon_id "ENSE00001916494.1"; level 2; protein_id "ENSP00000485269.1"; transcript_support_level "5"; hgnc_id "HGNC:14281"; tag "PAR"; havana_gene "OTTHUMG00000067432.3"; havana_transcript "OTTHUMT00000144414.2"; FI_gene_label "CRLF2^ENSG00000205755.12_PAR_Y"; orig_coord_info "chrY,1212556,1212723,-";
  Error, chr discrepancy in gtf info for chrY	HAVANA	exon	1208806	1208905	.	-	.	gene_id "CRLF2^ENSG00000205755.12_PAR_Y"; transcript_id "ENST00000467626.6_PAR_Y"; gene_type "protein_coding"; gene_name "CRLF2"; transcript_type "nonsense_mediated_decay"; transcript_name "CRLF2-204"; exon_number 2; exon_id "ENSE00001883966.1"; level 2; protein_id "ENSP00000485269.1"; transcript_support_level "5"; hgnc_id "HGNC:14281"; tag "PAR"; havana_gene "OTTHUMG00000067432.3"; havana_transcript "OTTHUMT00000144414.2"; FI_gene_label "CRLF2^ENSG00000205755.12_PAR_Y"; orig_coord_info "chrY,1208806,1208905,-";
  Error, chr discrepancy in gtf info for chrY	HAVANA	exon	1206433	1206599	.	-	.	gene_id "CRLF2^ENSG00000205755.12_PAR_Y"; transcript_id "ENST00000467626.6_PAR_Y"; gene_type "protein_coding"; gene_name "CRLF2"; transcript_type "nonsense_mediated_decay"; transcript_name "CRLF2-204"; exon_number 3; exon_id "ENSE00003755862.1"; level 2; protein_id "ENSP00000485269.1"; transcript_support_level "5"; hgnc_id "HGNC:14281"; tag "PAR"; havana_gene "OTTHUMG00000067432.3"; havana_transcript "OTTHUMT00000144414.2"; FI_gene_label "CRLF2^ENSG00000205755.12_PAR_Y"; orig_coord_info "chrY,1206433,1206599,-";
  Error, chr discrepancy in gtf info for chrY	HAVANA	exon	1202402	1202535	.	-	.	gene_id "CRLF2^ENSG00000205755.12_PAR_Y"; transcript_id "ENST00000467626.6_PAR_Y"; gene_type "protein_coding"; gene_name "CRLF2"; transcript_type "nonsense_mediated_decay"; transcript_name "CRLF2-204"; exon_number 4; exon_id "ENSE00003756004.1"; level 2; protein_id "ENSP00000485269.1"; transcript_support_level "5"; hgnc_id "HGNC:14281"; tag "PAR"; havana_gene "OTTHUMG00000067432.3"; havana_transcript "OTTHUMT00000144414.2"; FI_gene_label "CRLF2^ENSG00000205755.12_PAR_Y"; orig_coord_info "chrY,1202402,1202535,-";
  Error, chr discrepancy in gtf info for chrY	HAVANA	exon	1198801	1199145	.	-	.	gene_id "CRLF2^ENSG00000205755.12_PAR_Y"; transcript_id "ENST00000467626.6_PAR_Y"; gene_type "protein_coding"; gene_name "CRLF2"; transcript_type "nonsense_mediated_decay"; transcript_name "CRLF2-204"; exon_number 5; exon_id "ENSE00001837393.1"; level 2; protein_id "ENSP00000485269.1"; transcript_support_level "5"; hgnc_id "HGNC:14281"; tag "PAR"; havana_gene "OTTHUMG00000067432.3"; havana_transcript "OTTHUMT00000144414.2"; FI_gene_label "CRLF2^ENSG00000205755.12_PAR_Y"; orig_coord_info "chrY,1198801,1199145,-";
  Error, chr discrepancy in gtf info for chrY	HAVANA	exon	1196780	1196900	.	-	.	gene_id "CRLF2^ENSG00000205755.12_PAR_Y"; transcript_id "ENST00000467626.6_PAR_Y"; gene_type "protein_coding"; gene_name "CRLF2"; transcript_type "nonsense_mediated_decay"; transcript_name "CRLF2-204"; exon_number 6; exon_id "ENSE00003625623.1"; level 2; protein_id "ENSP00000485269.1"; transcript_support_level "5"; hgnc_id "HGNC:14281"; tag "PAR"; havana_gene "OTTHUMG00000067432.3"; havana_transcript "OTTHUMT00000144414.2"; FI_gene_label "CRLF2^ENSG00000205755.12_PAR_Y"; orig_coord_info "chrY,1196780,1196900,-";
  Error, chr discrepancy in gtf info for chrY	HAVANA	exon	1193218	1193302	.	-	.	gene_id "CRLF2^ENSG00000205755.12_PAR_Y"; transcript_id "ENST00000467626.6_PAR_Y"; gene_type "protein_coding"; gene_name "CRLF2"; transcript_type "nonsense_mediated_decay"; transcript_name "CRLF2-204"; exon_number 7; exon_id "ENSE00003757266.1"; level 2; protein_id "ENSP00000485269.1"; transcript_support_level "5"; hgnc_id "HGNC:14281"; tag "PAR"; havana_gene "OTTHUMG00000067432.3"; havana_transcript "OTTHUMT00000144414.2"; FI_gene_label "CRLF2^ENSG00000205755.12_PAR_Y"; orig_coord_info "chrY,1193218,1193302,-";
  Error, chr discrepancy in gtf info for chrY	HAVANA	exon	1190492	1191160	.	-	.	gene_id "CRLF2^ENSG00000205755.12_PAR_Y"; transcript_id "ENST00000467626.6_PAR_Y"; gene_type "protein_coding"; gene_name "CRLF2"; transcript_type "nonsense_mediated_decay"; transcript_name "CRLF2-204"; exon_number 8; exon_id "ENSE00003758632.1"; level 2; protein_id "ENSP00000485269.1"; transcript_support_level "5"; hgnc_id "HGNC:14281"; tag "PAR"; havana_gene "OTTHUMG00000067432.3"; havana_transcript "OTTHUMT00000144414.2"; FI_gene_label "CRLF2^ENSG00000205755.12_PAR_Y"; orig_coord_info "chrY,1190492,1191160,-";
  Error, chr discrepancy in gtf info for chrY	ENSEMBL	exon	1212556	1212634	.	-	.	gene_id "CRLF2^ENSG00000205755.12_PAR_Y"; transcript_id "ENST00000381567.8_PAR_Y"; gene_type "protein_coding"; gene_name "CRLF2"; transcript_type "protein_coding"; transcript_name "CRLF2-202"; exon_number 1; exon_id "ENSE00001603134.1"; level 3; protein_id "ENSP00000370979.4"; transcript_support_level "1"; hgnc_id "HGNC:14281"; tag "basic"; tag "CCDS"; tag "PAR"; ccdsid "CCDS75944.1"; havana_gene "OTTHUMG00000067432.3"; FI_gene_label "CRLF2^ENSG00000205755.12_PAR_Y"; orig_coord_info "chrY,1212556,1212634,-";
  Error, chr discrepancy in gtf info for chrY	ENSEMBL	exon	1206433	1206599	.	-	.	gene_id "CRLF2^ENSG00000205755.12_PAR_Y"; transcript_id "ENST00000381567.8_PAR_Y"; gene_type "protein_coding"; gene_name "CRLF2"; transcript_type "protein_coding"; transcript_name "CRLF2-202"; exon_number 2; exon_id "ENSE00003743277.1"; level 3; protein_id "ENSP00000370979.4"; transcript_support_level "1"; hgnc_id "HGNC:14281"; tag "basic"; tag "CCDS"; tag "PAR"; ccdsid "CCDS75944.1"; havana_gene "OTTHUMG00000067432.3"; FI_gene_label "CRLF2^ENSG00000205755.12_PAR_Y"; orig_coord_info "chrY,1206433,1206599,-";
  Error, chr discrepancy in gtf info for chrY	ENSEMBL	exon	1202402	1202535	.	-	.	gene_id "CRLF2^ENSG00000205755.12_PAR_Y"; transcript_id "ENST00000381567.8_PAR_Y"; gene_type "protein_coding"; gene_name "CRLF2"; transcript_type "protein_coding"; transcript_name "CRLF2-202"; exon_number 3; exon_id "ENSE00003756004.1"; level 3; protein_id "ENSP00000370979.4"; transcript_support_level "1"; hgnc_id "HGNC:14281"; tag "basic"; tag "CCDS"; tag "PAR"; ccdsid "CCDS75944.1"; havana_gene "OTTHUMG00000067432.3"; FI_gene_label "CRLF2^ENSG00000205755.12_PAR_Y"; orig_coord_info "chrY,1202402,1202535,-";
  Error, chr discrepancy in gtf info for chrY	ENSEMBL	exon	1198562	1198724	.	-	.	gene_id "CRLF2^ENSG00000205755.12_PAR_Y"; transcript_id "ENST00000381567.8_PAR_Y"; gene_type "protein_coding"; gene_name "CRLF2"; transcript_type "protein_coding"; transcript_name "CRLF2-202"; exon_number 4; exon_id "ENSE00001752466.1"; level 3; protein_id "ENSP00000370979.4"; transcript_support_level "1"; hgnc_id "HGNC:14281"; tag "basic"; tag "CCDS"; tag "PAR"; ccdsid "CCDS75944.1"; havana_gene "OTTHUMG00000067432.3"; FI_gene_label "CRLF2^ENSG00000205755.12_PAR_Y"; orig_coord_info "chrY,1198562,1198724,-";
  Error, chr discrepancy in gtf info for chrY	ENSEMBL	exon	1196780	1196900	.	-	.	gene_id "CRLF2^ENSG00000205755.12_PAR_Y"; transcript_id "ENST00000381567.8_PAR_Y"; gene_type "protein_coding"; gene_name "CRLF2"; transcript_type "protein_coding"; transcript_name "CRLF2-202"; exon_number 5; exon_id "ENSE00003755355.1"; level 3; protein_id "ENSP00000370979.4"; transcript_support_level "1"; hgnc_id "HGNC:14281"; tag "basic"; tag "CCDS"; tag "PAR"; ccdsid "CCDS75944.1"; havana_gene "OTTHUMG00000067432.3"; FI_gene_label "CRLF2^ENSG00000205755.12_PAR_Y"; orig_coord_info "chrY,1196780,1196900,-";
  Error, chr discrepancy in gtf info for chrY	ENSEMBL	exon	1193218	1193302	.	-	.	gene_id "CRLF2^ENSG00000205755.12_PAR_Y"; transcript_id "ENST00000381567.8_PAR_Y"; gene_type "protein_coding"; gene_name "CRLF2"; transcript_type "protein_coding"; transcript_name "CRLF2-202"; exon_number 6; exon_id "ENSE00003746279.1"; level 3; protein_id "ENSP00000370979.4"; transcript_support_level "1"; hgnc_id "HGNC:14281"; tag "basic"; tag "CCDS"; tag "PAR"; ccdsid "CCDS75944.1"; havana_gene "OTTHUMG00000067432.3"; FI_gene_label "CRLF2^ENSG00000205755.12_PAR_Y"; orig_coord_info "chrY,1193218,1193302,-";
  Error, chr discrepancy in gtf info for chrY	ENSEMBL	exon	1190897	1191160	.	-	.	gene_id "CRLF2^ENSG00000205755.12_PAR_Y"; transcript_id "ENST00000381567.8_PAR_Y"; gene_type "protein_coding"; gene_name "CRLF2"; transcript_type "protein_coding"; transcript_name "CRLF2-202"; exon_number 7; exon_id "ENSE00003734593.1"; level 3; protein_id "ENSP00000370979.4"; transcript_support_level "1"; hgnc_id "HGNC:14281"; tag "basic"; tag "CCDS"; tag "PAR"; ccdsid "CCDS75944.1"; havana_gene "OTTHUMG00000067432.3"; FI_gene_label "CRLF2^ENSG00000205755.12_PAR_Y"; orig_coord_info "chrY,1190897,1191160,-";
  Error, chr discrepancy in gtf info for chrY	CUSTOM	exon	1187549	1262723	.	-	.	gene_id "CRLF2^ENSG00000205755.12_PAR_Y"; transcript_id "ENSG00000205755.12_PAR_Y.trans.custom"; gene_type "protein_coding"; gene_name "CRLF2"; transcript_type "misc_RNA"; FI_gene_label "CRLF2^ENSG00000205755.12_PAR_Y"; orig_coord_info "chrY,1187549,1262723,-";
  Done.
  -parsing GTF file: finspector.gtf
  * Running CMD: /opt/conda/envs/nf-core-rnafusion-fusion-inspector_1.3.1-star2.7.0f/bin/STAR  --runThreadN 12  --genomeDir ctat_genome_lib_build_dir/ref_genome.fa.star.idx  --outSAMtype BAM SortedByCoordinate  --twopassMode Basic  --alignMatesGapMax 100000  --alignIntronMax 100000  --alignSJDBoverhangMin 10  --genomeSuffixLengthMax 10000 --limitBAMsortRAM 20000000000 --readFilesIn reads_1.fq.gz reads_2.fq.gz  --genomeFastaFiles fi_workdir/finspector.fa  --outSAMfilter KeepAllAddedReferences  --sjdbGTFfile fi_workdir/finspector.gtf  --alignSJstitchMismatchNmax 5 -1 5 5  --readFilesCommand 'gunzip -c' 
  
  EXITING because of FATAL ERROR: Genome version: 2.7.1a is INCOMPATIBLE with running STAR version: 2.7.0f
  SOLUTION: please re-generate genome from scratch with running version of STAR, or with version: 2.7.0d
  
  Apr 29 11:27:38 ...... FATAL ERROR, exiting
  
  gzip: stdout: Broken pipe
  
  gzip: Error, cmd: /opt/conda/envs/nf-core-rnafusion-fusion-inspector_1.3.1-star2.7.0f/bin/STAR  --runThreadN 12  --genomeDir ctat_genome_lib_build_dir/ref_genome.fa.star.idx  --outSAMtype BAM SortedByCoordinate  --twopassMode Basic  --alignMatesGapMax 100000  --alignIntronMax 100000  --alignSJDBoverhangMin 10  --genomeSuffixLengthMax 10000 --limitBAMsortRAM 20000000000 --readFilesIn reads_1.fq.gz reads_2.fq.gz  --genomeFastaFiles fi_workdir/finspector.fa  --outSAMfilter KeepAllAddedReferences  --sjdbGTFfile fi_workdir/finspector.gtf  --alignSJstitchMismatchNmax 5 -1 5 5  --readFilesCommand 'gunzip -c'  died with ret 26880 No such file or directory at /opt/conda/envs/nf-core-rnafusion-fusion-inspector_1.3.1-star2.7.0f/share/fusion-inspector-1.3.1-1/util/../PerlLib/Pipeliner.pm line 167.
  	Pipeliner::run(Pipeliner=HASH(0x562d935a8728)) called at /opt/conda/envs/nf-core-rnafusion-fusion-inspector_1.3.1-star2.7.0f/share/fusion-inspector-1.3.1-1/util/run_FI_STAR.pl line 292
  stdout: Broken pipe
  Traceback (most recent call last):
    File "/opt/conda/envs/nf-core-rnafusion-fusion-inspector_1.3.1-star2.7.0f/share/fusion-inspector-1.3.1-1/FusionInspector", line 944, in <module>
      FusionInspector().run()
    File "/opt/conda/envs/nf-core-rnafusion-fusion-inspector_1.3.1-star2.7.0f/share/fusion-inspector-1.3.1-1/FusionInspector", line 740, in run
      pipeliner.run()
    File "/opt/conda/envs/nf-core-rnafusion-fusion-inspector_1.3.1-star2.7.0f/share/fusion-inspector-1.3.1-1/PyLib/Pipeliner.py", line 53, in run
      run_cmd(cmd.get_cmd())
    File "/opt/conda/envs/nf-core-rnafusion-fusion-inspector_1.3.1-star2.7.0f/share/fusion-inspector-1.3.1-1/PyLib/Pipeliner.py", line 17, in run_cmd
      subprocess.check_call(cmd, shell=True)
    File "/opt/conda/envs/nf-core-rnafusion-fusion-inspector_1.3.1-star2.7.0f/lib/python2.7/subprocess.py", line 190, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '/opt/conda/envs/nf-core-rnafusion-fusion-inspector_1.3.1-star2.7.0f/share/fusion-inspector-1.3.1-1/util/run_FI_STAR.pl --genome ctat_genome_lib_build_dir/ref_genome.fa --patch fi_workdir/finspector.fa -G fi_workdir/finspector.gtf --CPU 12 --out_prefix finspector.star --out_dir fi_workdir --reads "reads_1.fq.gz reads_2.fq.gz"' returned non-zero exit status 2

Work dir:
  /data1/maxime/rnafusion/work/29/a0c20176e79b59502cf3cde239f71a

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

**Comment by matq007** [comment]
Found the problem:
```
aws s3 ls s3://ngi-igenomes/igenomes/Homo_sapiens/NCBI/GRCh38/Annotation/CTAT/GRCh38_gencode_v32_CTAT_lib_Dec062019.tar.xz
```

Only `STAR-Fusion 1.8` is compatible with that genome. Let's see if we can keep the STAR aligner or we have to fix it for all.
