### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by Dagsbio** [nf-core/rnafusion#177]
On a cluster (20 nodes, 36cores per node, 192 GB RAM per node) I launched this command:

```
**sbatch -p cpu36c -n 322 --mail-user=dagsbio@gmail.com -e ERRORES_SG.txt -o RESULTADOS_SG.txt ./nextflow run rnafusion/ -profile singularity  --genomes_base cosas_rnafusion/ --reads 'sg/*_R{1,2}.fastq.gz' --arriba --star_fusion --fusioncatcher --ericscript --pizzly --squid --fusion_inspector --outdir SG_RESULTS/ --star_index cosas_rnafusion/star-index/**
```

After a while, I am getting this error:

```
**Error executing process > 'summary (TP99)'

Caused by:
  Process `summary (TP99)` terminated with an error exit status (1)

Command executed:

  fusion_report run TP99 . cosas_rnafusion//databases \
      --arriba TP99_arriba.tsv --ericscript TP99_ericscript.tsv --fusioncatcher TP99_fusioncatcher.txt --pizzly TP99_pizzly.txt --squid TP99_fusions_annotated.txt --starfusion TP99_star-fusion.tsv  
  mv fusion_list.tsv TP99_fusion_list.tsv
  mv fusion_genes_mqc.json TP99_fusion_genes_mqc.json

Command exit status:
  1

Command output:
  Running application...
  unable to open database file
  Traceback (most recent call last):
    File "/opt/conda/envs/nf-core-rnafusion-1.2.0/lib/python3.7/site-packages/fusion_report/common/db.py", line 37, in connect
      connection = sqlite3.connect(os.path.join(path, database))
  sqlite3.OperationalError: unable to open database file
```
  
  During handling of the above exception, another exception occurred:
  
```
  Traceback (most recent call last):
    File "/opt/conda/envs/nf-core-rnafusion-1.2.0/lib/python3.7/site-packages/fusion_report/app.py", line 60, in run
      self.preprocess(params)
    File "/opt/conda/envs/nf-core-rnafusion-1.2.0/lib/python3.7/site-packages/fusion_report/app.py", line 82, in preprocess
      self.enrich(params.db_path)
    File "/opt/conda/envs/nf-core-rnafusion-1.2.0/lib/python3.7/site-packages/fusion_report/app.py", line 140, in enrich
      FusionGDB(path).name: FusionGDB(path).get_all_fusions(),
    File "/opt/conda/envs/nf-core-rnafusion-1.2.0/lib/python3.7/site-packages/fusion_report/common/singleton.py", line 11, in __call__
      cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
    File "/opt/conda/envs/nf-core-rnafusion-1.2.0/lib/python3.7/site-packages/fusion_report/data/fusiongdb.py", line 13, in __init__
      super().__init__(path, Settings.FUSIONGDB['NAME'], Settings.FUSIONGDB['SCHEMA'])
    File "/opt/conda/envs/nf-core-rnafusion-1.2.0/lib/python3.7/site-packages/fusion_report/common/db.py", line 25, in __init__
      self.connection = self.connect(path, self.database)
    File "/opt/conda/envs/nf-core-rnafusion-1.2.0/lib/python3.7/site-packages/fusion_report/common/db.py", line 41, in connect
      raise DbException(ex)
  fusion_report.common.exceptions.db.DbException: unable to open database file**
```

EDIT: formatting

**Comment by MaxUlysse** [comment]
Have you tried `--star_index cosas_rnafusion/star-index` instead of `--star_index cosas_rnafusion/star-index/**` not sure about the `**` part.

**Comment by matq007** [comment]
Make sure your `--genomes_base` contains the proper path to `databases` folder. It should contain files with `.db` extension.

**Comment by Dagsbio** [comment]
Hi, I got these databases there: 


cosmic.db
fusiongdb.db
mitelman.db

Am I missing any?

At this point I managed somehow to run every tool except getting the summary report:



![image](https://user-images.githubusercontent.com/23311037/106904411-72931b80-66fb-11eb-82e3-914b85edbb32.png)

**Comment by matq007** [comment]
You can see that you have `cosas_rnafusion//databases` should be `cosas_rnafusion/databases`. Guessing that should be the problem.
