### ISSUE TITLE
HTTP Error 404 during `fusion_report download`

### ISSUE THREAD

**Issue by yuifu** [nf-core/rnafusion#187]
Hi! I got an error regarding HTTP Error 404 during `fusion_report download`. Is there any way to resolve this error?
(I confirmed that your COSMIC user ID and password are correct.)

The command is as follows:

```bash
nextflow run nf-core/rnafusion/download-references.nf -profile singularity \
  --base \
  --star_fusion \
  --fusion_report \
  --outdir rnafusion_references_test002 \
  --cosmic_usr <e-mail address> --cosmic_passwd <PASSWORD>
```

`.command.out`:

```
Downloading resources...
Downloading db.tar.gz
HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/opt/conda/envs/nf-core-rnafusion-1.2.0/lib/python3.7/site-packages/fusion_report/common/net.py", line 50, in get_large_file
    with urllib.request.urlopen(url, context=ctx) as response:
  File "/opt/conda/envs/nf-core-rnafusion-1.2.0/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/envs/nf-core-rnafusion-1.2.0/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/opt/conda/envs/nf-core-rnafusion-1.2.0/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/conda/envs/nf-core-rnafusion-1.2.0/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/opt/conda/envs/nf-core-rnafusion-1.2.0/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/opt/conda/envs/nf-core-rnafusion-1.2.0/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/nf-core-rnafusion-1.2.0/lib/python3.7/site-packages/fusion_report/app.py", line 70, in run
    Download(params)
  File "/opt/conda/envs/nf-core-rnafusion-1.2.0/lib/python3.7/site-packages/fusion_report/download.py", line 25, in __init__
    self.download_all(params)
  File "/opt/conda/envs/nf-core-rnafusion-1.2.0/lib/python3.7/site-packages/fusion_report/download.py", line 46, in download_all
    Net.get_cosmic(self.cosmic_token, return_err)
  File "/opt/conda/envs/nf-core-rnafusion-1.2.0/lib/python3.7/site-packages/fusion_report/common/net.py", line 81, in get_cosmic
    Net.get_large_file(auth_url)
  File "/opt/conda/envs/nf-core-rnafusion-1.2.0/lib/python3.7/site-packages/fusion_report/common/net.py", line 59, in get_large_file
    raise DownloadException(ex)
fusion_report.common.exceptions.download.DownloadException: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/nf-core-rnafusion-1.2.0/bin/fusion_report", line 13, in <module>
    app.run()
  File "/opt/conda/envs/nf-core-rnafusion-1.2.0/lib/python3.7/site-packages/fusion_report/app.py", line 77, in run
    raise AppException(ex)
fusion_report.common.exceptions.app.AppException: HTTP Error 404: Not Found
```

Version info

```
  nf-core/rnafusion v1.2.0
----------------------------------------------------
Pipeline Name     : nf-core/rnafusion/download-references.nf
Pipeline Version  : 1.2.0
References        : Reference v97, STAR-Fusion, fusion-report
Container         : docker - nfcore/rnafusion:1.2.0
Max Resources     : 128 GB memory, 16 cpus, 10d time per job
Output dir        : rnafusion_references_test002
User              : harukao
----------------------------------------------------
```

**Comment by Bontempogianpaolo1** [comment]
Hi,

I have got the same error. 

Could you fix it please? If not, let us know! It could be very helpful!
