### ISSUE TITLE
Error executing process > 'NFCORE_RNAFUSION:RNAFUSION:FUSIONREPORT_WORKFLOW:FUSIONREPORT (test)'

### ISSUE THREAD

**Issue by valleema** [nf-core/rnafusion#232]
### Description of the bug

The test command does not succeed.

### Command used and terminal output

```console
~/bin/nextflow-22.04.0-all run main.nf -profile test,singularity --outdir /home/valleema/nf-core/rnafusion-2.0.0 -resume

Error executing process > 'NFCORE_RNAFUSION:RNAFUSION:FUSIONREPORT_WORKFLOW:FUSIONREPORT (test)'

Caused by:
  Process `NFCORE_RNAFUSION:RNAFUSION:FUSIONREPORT_WORKFLOW:FUSIONREPORT (test)` terminated with an error exit status (1)

Command executed:

  fusion_report run test . fusion_report_db  --allow-multiple-gene-symbols
  
  mv fusion_list.tsv test.fusionreport.tsv
  mv fusion_list_filtered.tsv test.fusionreport_filtered.tsv
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_RNAFUSION:RNAFUSION:FUSIONREPORT_WORKFLOW:FUSIONREPORT":
      fusion_report: $(fusion_report --version)
  END_VERSIONS

Command exit status:
  1

Command output:
  Running application...
  unable to open database file
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5u-py3.9.egg/fusion_report/common/db.py", line 38, in connect
      connection = sqlite3.connect(os.path.join(path, database))
  sqlite3.OperationalError: unable to open database file
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5u-py3.9.egg/fusion_report/app.py", line 61, in run
      self.preprocess(params)
    File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5u-py3.9.egg/fusion_report/app.py", line 83, in preprocess
      self.enrich(params.db_path)
    File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5u-py3.9.egg/fusion_report/app.py", line 141, in enrich
      CosmicDB(path).name: CosmicDB(path).get_all_fusions(),
    File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5u-py3.9.egg/fusion_report/common/singleton.py", line 11, in __call__
      cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
    File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5u-py3.9.egg/fusion_report/data/cosmic.py", line 15, in __init__
      super().__init__(path, Settings.COSMIC['NAME'], Settings.COSMIC['SCHEMA'])
    File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5u-py3.9.egg/fusion_report/common/db.py", line 26, in __init__
      self.connection = self.connect(path, self.database)
    File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5u-py3.9.egg/fusion_report/common/db.py", line 42, in connect
      raise DbException(ex)
  fusion_report.common.exceptions.db.DbException: unable to open database file
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5u-py3.9.egg/EGG-INFO/scripts/fusion_report", line 13, in <module>
      app.run()
    File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5u-py3.9.egg/fusion_report/app.py", line 78, in run
      raise AppException(ex)
  fusion_report.common.exceptions.app.AppException: unable to open database file

Command error:
  unable to open database file

Work dir:
  /home/valleema/work/c1/75a67af618e1c77c848a772c79e9f3

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

### System information

- Nextflow version: 22.04.0
- Hardware: HPC
- Executor: OAR
- Container engine: Singularity
- OS: Debian 9
- Version of nf-core/rnafusion: 2.0.0

**Comment by rannick** [comment]
That is unfortunately to be expected because the test is only a fusion detection test. You still need to build the references by running the pipeline with --build_references before running the test

**Comment by valleema** [comment]
I did build the references beforehand...

**Comment by rannick** [comment]
Then you need to feed the `--genomes_base PATH ` parameter

**Comment by valleema** [comment]
Sure:

```
~/bin/nextflow-22.04.0-all run main.nf -profile singularity --build_references --outdir /home/valleema/nf-core/rnafusion-2.0.0
```

**Comment by rannick** [comment]
Good point, I should update the usage documentation. 
You need a COSMIC username and password:
`--cosmic_username XXXX --cosmic_passwd YYYY`

**Comment by valleema** [comment]
Yes, it goes through for this step (maybe put a warning in the documentation that COSMIC might send a confirmation e-mail as well - won't work if not verified).
I still cannot go through the reference building, as I am trying to pull Singularity images with `nf-core download` as you advise in the docs (no container is downloading / building):

```
nf-core download rnafusion -s

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'


INFO: Saving rnafusion
 Pipeline release: 2.0.0
 Pull singularity containers: Yes
 Output file: nf-core-rnafusion-2.0.0.tar.gz

INFO: Downloading workflow files from GitHub

INFO: Downloading centralised configs from GitHub

INFO: No container names found in workflow

INFO: Compressing download..

INFO: Command to extract files: tar -xzf nf-core-rnafusion-2.0.0.tar.gz

INFO: MD5 checksum for nf-core-rnafusion-2.0.0.tar.gz: ccb1a42e16f977fe9369a3a502384d17
```

Would it require a new issue? Maybe at the nf-core tools repo?

**Comment by rannick** [comment]
Good point about COSMIC, I will create a documentation issue. 
So I have never tested the singularity download this way. That part of the documentation comes from nf-core templates and it might be an older template paragraph slipped through, I will investigate, but I would recommend in the meantime to maybe use the environment variable NXF_SINGULARITY_CACHEDIR if you want to cache the containers and run the pipeline directly.

**Comment by valleema** [comment]
I could pull on another machine and then scp the image, it works.
Thank you for your help!!
