### ISSUE TITLE
FusionInspector attempting to run wrong fastq from another sample

### ISSUE THREAD

**Issue by ojziff** [nf-core/rnafusion#247]
### Description of the bug

Hi, 

Sorry, another bug has popped up. I tried to run rnafusion on 429 samples. 30/429 are single-end. I got this concerning error with `FUSIONINSPECTOR` process - it is attempting to the paired-end sample_249 with the wrong fastq from single-end sample_423.

I have checked that the samplesheet is correct and that STARFUSION process did also not make this same error.

### Command used and terminal output

```console
nextflow run nf-core/rnafusion --input samplesheet.csv --outdir rnafusion --genomes_base rnafusion/references --starfusion --fusionreport -profile crick -r 2.0.0
```

### Terminal Ouput
```
Error executing process > 'NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:FUSIONINSPECTOR (sample_249)'

Caused by:
  Process `NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:FUSIONINSPECTOR (sample_249)` terminated with an error exit status (1)

Command executed:

  FusionInspector \
      --fusions sample_249.fusionreport.tsv \
      --genome_lib ctat_genome_lib_build_dir \
      --left_fq sample_423.fastq.gz --right_fq null \
      --CPU 12 \
      -O . \
      --out_prefix sample_249 \
      --vis 
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:FUSIONINSPECTOR":
      STAR-Fusion: $(echo STAR-Fusion --version 2>&1 | grep -i 'version' | sed 's/STAR-Fusion version: //')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  Error, cannot locate file: null
  
  Traceback (most recent call last):
    File "/usr/local/src/STAR-Fusion/FusionInspector/FusionInspector", line 1883, in 
      FusionInspector().run()
    File "/usr/local/src/STAR-Fusion/FusionInspector/FusionInspector", line 558, in run
      check_files_exist([fq_filename])
    File "/usr/local/src/STAR-Fusion/FusionInspector/FusionInspector", line 1737, in check_files_exist
      raise RuntimeError("Error, missing files as indicated")
  RuntimeError: Error, missing files as indicated
```
```


### Relevant files

_No response_

### System information

_No response_

**Comment by matq007** [comment]
We will drop the single-read support. In the meantime just remove the single-read ones from the samplesheet.

**Comment by rannick** [comment]
I suspect this specific issue is resolved by #252, try with `-r fusioninspector_samplemix`. But as Martin said, no guarantees for single-read at the moment

**Comment by rannick** [comment]
Single-read documentation updated and fusioninspector mixup fix merged in dev
