### ISSUE TITLE
Fusionreport required 1 positional argument "filename"

### ISSUE THREAD

**Issue by apeltzer** [nf-core/rnafusion#328]
### Description of the bug

TypeError: include_raw() missing 1 required positional argument: 'filename'

### Command used and terminal output

```console
simply run workflow, fusionreport on `dev` fails then.
```

**Comment by apeltzer** [comment]
Error message:

```
EEF1D--DLD
pizzly
Traceback (most recent call last):
  File "/usr/local/bin/fusion_report", line 4, in <module>
    __import__('pkg_resources').run_script('fusion-report==2.1.5', 'fusion_report')
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5-py3.9.egg/EGG-INFO/scripts/fusion_report", line 13, in <module>
    app.run()
  File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5-py3.9.egg/fusion_report/app.py", line 62, in run
    self.generate_report(params)
  File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5-py3.9.egg/fusion_report/app.py", line 97, in generate_report
    report.render(index_page)
  File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5-py3.9.egg/fusion_report/common/report.py", line 70, in render
    super().render(page, template_variables)
  File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5-py3.9.egg/fusion_report/common/template.py", line 44, in render
    view = self.j2_env.get_template(page.view).render(merged_variables)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5-py3.9.egg/fusion_report/templates/views/index.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5-py3.9.egg/fusion_report/templates/layout.html", line 10, in top-level template code
    {% block head %}{% endblock %}
  File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5-py3.9.egg/fusion_report/templates/views/index.html", line 4, in block 'head'
    {{ include_raw('assets/css/bootstrap-4.3.1.min.css') | safe }}
TypeError: include_raw() missing 1 required positional argument: 'filename'
```

**Comment by apeltzer** [comment]
This looks actually like a bug in `fusion_report`

**Comment by apeltzer** [comment]
https://github.com/Clinical-Genomics/fusion-report/blob/mittelman_fix/fusion_report/templates/views/index.html

**Comment by rannick** [comment]
I can reproduce

**Comment by rannick** [comment]
This should solve the problem: https://github.com/nf-core/rnafusion/pull/331
