### ISSUE TITLE
Configobject Illegal Argument Exception issue (likely with squid?)

### ISSUE THREAD

**Issue by apeltzer** [nf-core/rnafusion#329]
### Description of the bug

Mar-10 09:04:59.179 [Actor Thread 75] INFO  nextflow.processor.TaskProcessor - [1a/148078] Cached process > NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:ARRIBA_VISUALISATION (TMG301_82_S47)
Mar-10 09:04:59.181 [Actor Thread 77] INFO  nextflow.processor.TaskProcessor - [35/5e1a70] Cached process > NFCORE_RNAFUSION:RNAFUSION:STRINGTIE_WORKFLOW:STRINGTIE_MERGE (7)
Mar-10 09:04:59.182 [Actor Thread 53] ERROR nextflow.processor.TaskProcessor - Execution aborted due to an unexpected error
java.lang.IllegalArgumentException: Cannot compare groovy.util.ConfigObject with value '[:]' and java.lang.Integer with value '2'
        at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.compareToWithEqualityCheck(DefaultTypeTransformation.java:608)
        at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.compareTo(DefaultTypeTransformation.java:537)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.compareTo(ScriptBytecodeAdapter.java:716)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.compareLessThanEqual(ScriptBytecodeAdapter.java:751)
        at Script8E2AF1CC66994A17F6237BD82FB7F30B$_run_closure1$_closure2.doCall(Script8E2AF1CC66994A17F6237BD82FB7F30B:6)
        at Script8E2AF1CC66994A17F6237BD82FB7F30B$_run_closure1$_closure2.doCall(Script8E2AF1CC66994A17F6237BD82FB7F30B)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:406)
        at nextflow.processor.LazyMap.resolveImpl(TaskConfig.groovy:613)
        at nextflow.processor.LazyMap.resolveImpl(TaskConfig.groovy)
        at nextflow.processor.LazyMap.resolve(TaskConfig.groovy:574)
        at nextflow.processor.LazyMap.getValue(TaskConfig.groovy:641)
        at nextflow.processor.LazyMap.get(TaskConfig.groovy:636)
        at nextflow.processor.TaskConfig.get(TaskConfig.groovy:152)
        at nextflow.processor.TaskConfig.getErrorStrategy(TaskConfig.groovy:225)

### Command used and terminal output

```console
See slack for discusison
```

**Comment by apeltzer** [comment]
The error does not occur, when i restrict to run without squid.

**Comment by maxulysse** [comment]
Do you still have the error with only squid?

**Comment by apeltzer** [comment]
Yeah not sure, I can give it a try once this run finished

**Comment by apeltzer** [comment]
Last step running is SAMTOOLS_VIEW_FOR_SQUID, so I had a look at the command.sh for that one:

```
![image](https://user-images.githubusercontent.com/2359510/224373287-dd5cf8ad-eeae-4ea6-84ab-9a6dd0b1ba9d.png)

```
That looks a bit weird to me to have twice the `-o `in the params no?

**Comment by maxulysse** [comment]
that looks weird indeed, 2 `-o`, and 3 different outputs

**Comment by rannick** [comment]
https://github.com/nf-core/rnafusion/pull/330
