### ISSUE TITLE
Fusionreport download Issue

### ISSUE THREAD

**Issue by shwcha9** [nf-core/rnafusion#397]
### Description of the bug

I am trying to download references by running build_references.nf pipeline. Fusionreport tool throws the following error:
Please let me know how I can resolve this issue.
Thanks.

### Command used and terminal output

```console
Command: nextflow run . -profile azure --outdir 'path/to/output' --build_references --all --genomes_base 'path/to/references'  -w 'path/to/work' -c config

Downloading resources...
Downloading mitelman_db.zip
near "VALUES": syntax error
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5-py3.9.egg/fusion_report/common/db.py", line 71, in setup
    self.connection.executemany(
sqlite3.OperationalError: near "VALUES": syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5-py3.9.egg/fusion_report/app.py", line 71, in run
    Download(params)
  File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5-py3.9.egg/fusion_report/download.py", line 22, in __init__
    self.download_all(params)
  File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5-py3.9.egg/fusion_report/download.py", line 41, in download_all
    Net.get_mitelman(self, return_err)
  File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5-py3.9.egg/fusion_report/common/net.py", line 211, in get_mitelman
    db.setup(files, delimiter='\t', skip_header=False, encoding='ISO-8859-1')
  File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5-py3.9.egg/fusion_report/common/db.py", line 78, in setup
    raise DbException(ex)
fusion_report.common.exceptions.db.DbException: near "VALUES": syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5-py3.9.egg/EGG-INFO/scripts/fusion_report", line 13, in <module>
    app.run()
  File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5-py3.9.egg/fusion_report/app.py", line 78, in run
    raise AppException(ex)
fusion_report.common.exceptions.app.AppException: near "VALUES": syntax error
```

**Comment by rannick** [comment]
Same as https://github.com/nf-core/rnafusion/issues/377, merged to dev and will be in next release

**Comment by shwcha9** [comment]
When running fusionreport reference download with the new docker image docker.io/clinicalgenomics/fusion-report:2.1.5p3. I face another error.

<urlopen error [Errno -5] No address associated with hostname>
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1034, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 974, in send
    self.connect()
  File "/usr/local/lib/python3.9/http/client.py", line 1441, in connect
    super().connect()
  File "/usr/local/lib/python3.9/http/client.py", line 945, in connect
    self.sock = self._create_connection(
  File "/usr/local/lib/python3.9/socket.py", line 823, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname
