### ISSUE TITLE
java.lang.NoSuchMethodError: 'com.fasterxml.jackson.core.io.ContentReference com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createContentReference(java.lang.Object)'

### ISSUE THREAD

**Issue by maressyl** [nf-core/rnafusion#411]
### Description of the bug

Running the last 2.4.0 release with Tower triggers an error.

### Command used and terminal output

```bash
./nextflow-23.04.4-all -c HCL.conf run maressyl/rnafusion -r 2.4.0-HCL -profile singularity --outdir build --pizzly --starfusion --fusioncatcher --arriba --build_references --cosmic_username "REDACTED" --cosmic_passwd "REDACTED"
```
```
Sep-28 12:24:20.514 [main] ERROR nextflow.cli.Launcher - @unknown
java.lang.NoSuchMethodError: 'com.fasterxml.jackson.core.io.ContentReference com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createContentReference(java.lang.Object)'
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:413)
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:15)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3561)
        at org.apache.groovy.yaml.util.YamlConverter.convertYamlToJson(YamlConverter.java:42)
        at groovy.yaml.YamlSlurper.parse(YamlSlurper.java:61)
        at groovy.yaml.YamlSlurper.parse(YamlSlurper.java:71)
        at groovy.yaml.YamlSlurper.parse(YamlSlurper.java:92)
        at io.seqera.tower.plugin.TowerReports.parseReportEntries(TowerReports.groovy:155)
        at io.seqera.tower.plugin.TowerReports.flowCreate(TowerReports.groovy:65)
        at io.seqera.tower.plugin.TowerClient.onFlowCreate(TowerClient.groovy:295)
        at nextflow.Session$_notifyFlowCreate_closure23.doCall(Session.groovy:1054)
        at nextflow.Session$_notifyFlowCreate_closure23.call(Session.groovy)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2357)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2342)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2383)
        at nextflow.Session.notifyFlowCreate(Session.groovy:1054)
        at nextflow.Session.start(Session.groovy:517)
        at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:125)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:368)
        at nextflow.cli.Launcher.run(Launcher.groovy:494)
        at nextflow.cli.Launcher.main(Launcher.groovy:665)
```

### Relevant files

`HCL.conf`
```
singularity.envWhitelist = "http_proxy,https_proxy"

tower {
  enabled = true
  accessToken = 'REDACTED'
  workspaceId = 'REDACTED'
}
```

### System information

- Nextflow 23.04.4-all ([as used in CI](https://github.com/nf-core/rnafusion/blob/dev/.github/workflows/ci.yml#L27))
- HPC
- local executor
- singularity-ce version 3.8.0
- Debian 11
- nf-core/rnafusion 2.4.0 [with a minor tweak](https://github.com/maressyl/rnafusion/tree/2.4.0-HCL)

**Comment by maressyl** [comment]
Running with `tower.enabled = false` does not trigger the error.

**Comment by maressyl** [comment]
It seems to work with the lastest Nextflow pre-release (`nextflow-23.09.2-edge-all`), it would be reassuring to use a Nextflow version for which automated tests pass though.

**Comment by rannick** [comment]
Hi Sylvain, just to let you know that I have seen this, but I am not sure yet how to fix it. I want to merge the new template first and check then

**Comment by maressyl** [comment]
No problem, this one can be worked around. Good luck !

**Comment by rannick** [comment]
What version of tower are you using? I am wondering if that could be the issue

**Comment by rannick** [comment]
As the linked issue says: "this is a problem with Nextflows Tower plugin and its dependencies" and not a problem of rnafusion, I will close this
