### ISSUE TITLE
rnafusion v2.4.0: HTTP Error 404 during fusion_report download

### ISSUE THREAD

**Issue by lconde-ucl** [nf-core/rnafusion#419]
### Description of the bug

The pipeline fails while building the references at NFCORE_RNAFUSION:BUILD_REFERENCES:FUSIONREPORT_DOWNLOAD  with "HTTP Error 404: Not Found" errors

### Command used and terminal output

```console
Command used:
-------------
nextflow run /shared/ucl/depts/cancer/apps/nfcore/rnafusion/2.4.0/workflow/
 -profile myriad
 --build_references --all
 --outdir results
 --genome GRCh38
 --cosmic_username XXXXXXXX --cosmic_passwd 'XXXXXXX'
 -resume -with-tower

Error:
------

ERROR ~ Error executing process > 'NFCORE_RNAFUSION:BUILD_REFERENCES:FUSIONREPORT_DOWNLOAD (fusionreport)'

Caused by:
  Process `NFCORE_RNAFUSION:BUILD_REFERENCES:FUSIONREPORT_DOWNLOAD (fusionreport)` terminated with an error exit status (1)

Command executed:

  fusion_report download --cosmic_usr "XXXXXXXXX" --cosmic_passwd "XXXXXXXXX"  ./
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_RNAFUSION:BUILD_REFERENCES:FUSIONREPORT_DOWNLOAD":
      fusion_report: $(fusion_report --version | sed 's/fusion-report //')
  END_VERSIONS

Command exit status:
  1

Command output:
  Downloading mitelman_db.zip
  Downloading TCGA_ChiTaRS_combined_fusion_information_on_hg19.txt
  Downloading TCGA_ChiTaRS_combined_fusion_ORF_analyzed_gencode_h19v19.txt
  Downloading uniprot_gsymbol.txt
  Downloading fusion_uniprot_related_drugs.txt
  Downloading fusion_ppi.txt
  Downloading fgene_disease_associations.txt
  Downloading FusionGDB2_id.xlsx
  Downloading resources from SANGER...
  HTTP Error 404: Not Found
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5-py3.9.egg/fusion_report/common/net.py", line 103, in get_large_file
      with urllib.request.urlopen(req, context=ctx) as response:
    File "/usr/local/lib/python3.9/urllib/request.py", line 214, in urlopen
      return opener.open(url, data, timeout)
    File "/usr/local/lib/python3.9/urllib/request.py", line 523, in open
      response = meth(req, response)
    File "/usr/local/lib/python3.9/urllib/request.py", line 632, in http_response
      response = self.parent.error(
    File "/usr/local/lib/python3.9/urllib/request.py", line 561, in error
      return self._call_chain(*args)
    File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
      result = func(*args)
    File "/usr/local/lib/python3.9/urllib/request.py", line 641, in http_error_default
      raise HTTPError(req.full_url, code, msg, hdrs, fp)
  urllib.error.HTTPError: HTTP Error 404: Not Found
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5-py3.9.egg/fusion_report/app.py", line 71, in run
      Download(params)
    File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5-py3.9.egg/fusion_report/download.py", line 22, in __init__
      self.download_all(params)
    File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5-py3.9.egg/fusion_report/download.py", line 55, in download_all
      Net.get_cosmic_from_sanger(self.cosmic_token, return_err)
    File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5-py3.9.egg/fusion_report/common/net.py", line 134, in get_cosmic_from_sanger
      Net.get_large_file(auth_url)
    File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5-py3.9.egg/fusion_report/common/net.py", line 112, in get_large_file
      raise DownloadException(ex)
  fusion_report.common.exceptions.download.DownloadException: HTTP Error 404: Not Found
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5-py3.9.egg/EGG-INFO/scripts/fusion_report", line 13, in <module>
      app.run()
    File "/usr/local/lib/python3.9/site-packages/fusion_report-2.1.5-py3.9.egg/fusion_report/app.py", line 78, in run
      raise AppException(ex)
  fusion_report.common.exceptions.app.AppException: HTTP Error 404: Not Found

Command error:
  HTTP Error 404: Not Found
```

### System information

Nextflow version: 23.04.4
Executor: sge
Container Engine: singularoty
OS: Red Hat Linux
Version of nf-core/rnafusion: v2.4.0

**Comment by rannick** [comment]
Fixed by https://github.com/nf-core/rnafusion/pull/420
