### ISSUE TITLE
Error in NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:VCF_COLLECT

### ISSUE THREAD

**Issue by vwucher** [nf-core/rnafusion#460]
### Description of the bug

Hi,
I am currently trying to run `rnafusion 3.0.1` on patient samples, but it crashes during the `NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:VCF_COLLECT` process.
I can make it work if I use the `--skip_vis` option, but I would like to have at least the visualisation of `Arriba`.

Since it is for diagnosis, it is targeted RNA-seq and it is also possible that for some samples there is no fusion detected, I don't know if it can be the issue.

I don't know if it possible to either fix this or skip this process only (and not the `Arriba` visualisation).

Thanks in advance for your help!

### Command used and terminal output

```console
bash ./nextflow-23.10.0-all run nf-core/rnafusion \
    -r 3.0.1 \
    -latest \
    -c HCL.conf \
    -profile singularity \
    -resume \
    --input input/$ticket/samplesheet.csv \
    --outdir output/$ticket \
    --genomes_base /srv/scratch/rnafusion_3/build/references \
    --all

[...]

-[nf-core/rnafusion] Pipeline completed with errors-
-[nf-core/rnafusion] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:VCF_COLLECT (C469T-23EH16313-0-RUBAN-LIG1H)'

Caused by:
  Process `NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:VCF_COLLECT (C469T-23EH16313-0-RUBAN-LIG1H)` terminated with an error exit status (1)

Command executed:

  vcf_collect.py --fusioninspector C469T-23EH16313-0-RUBAN-LIG1H.FusionInspector.fusions.abridged.tsv.annotated.coding_effect --fusionreport C469T-23EH16313-0-RUBAN-LIG1H_fusionreport_index.html --fusioninspector_gtf C469T-23EH16313-0-RUBAN-LIG1H.tsv --fusionreport_csv C469T-23EH16313-0-RUBAN-LIG1H.fusions.csv --hgnc hgnc_complete_set.txt --sample C469T-23EH16313-0-RUBAN-LIG1H --out C469T-23EH16313-0-RUBAN-LIG1H_fusion_data.vcf
  gzip C469T-23EH16313-0-RUBAN-LIG1H_fusion_data.vcf

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:VCF_COLLECT":
      python: $(python --version | sed 's/Python //g')
      HGNC DB retrieval: $(cat HGNC-DB-timestamp.txt)
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/home/chu-lyon.fr/wucherex/.nextflow/assets/nf-core/rnafusion/bin/vcf_collect.py", line 505, in <module>
      sys.exit(main())
               ^^^^^^
    File "/home/chu-lyon.fr/wucherex/.nextflow/assets/nf-core/rnafusion/bin/vcf_collect.py", line 493, in main
      vcf_collect(
    File "/home/chu-lyon.fr/wucherex/.nextflow/assets/nf-core/rnafusion/bin/vcf_collect.py", line 41, in vcf_collect
      build_fusioninspector_dataframe(fusioninspector_in_file)
    File "/home/chu-lyon.fr/wucherex/.nextflow/assets/nf-core/rnafusion/bin/vcf_collect.py", line 275, in build_fusioninspector_dataframe
      df[["ChromosomeA", "PosA", "Strand1"]] = df["LeftBreakpoint"].str.split(":", expand=True)
      ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/pandas/core/frame.py", line 3966, in __setitem__
      self._setitem_array(key, value)
    File "/usr/local/lib/python3.11/site-packages/pandas/core/frame.py", line 4008, in _setitem_array
      check_key_length(self.columns, key, value)
    File "/usr/local/lib/python3.11/site-packages/pandas/core/indexers/utils.py", line 401, in check_key_length
      raise ValueError("Columns must be same length as key")
  ValueError: Columns must be same length as key

Work dir:
  /srv/scratch/rnafusion_3/work/8c/6fd61a80d27d92b5bb9e288efaf8ae

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
  File "/home/chu-lyon.fr/wucherex/.nextflow/assets/nf-core/rnafusion/bin/vcf_collect.py", line 505, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/chu-lyon.fr/wucherex/.nextflow/assets/nf-core/rnafusion/bin/vcf_collect.py", line 493, in main
    vcf_collect(
  File "/home/chu-lyon.fr/wucherex/.nextflow/assets/nf-core/rnafusion/bin/vcf_collect.py", line 41, in vcf_collect
    build_fusioninspector_dataframe(fusioninspector_in_file)
  File "/home/chu-lyon.fr/wucherex/.nextflow/assets/nf-core/rnafusion/bin/vcf_collect.py", line 275, in build_fusioninspector_dataframe
    df[["ChromosomeA", "PosA", "Strand1"]] = df["LeftBreakpoint"].str.split(":", expand=True)
    ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/core/frame.py", line 3966, in __setitem__
    self._setitem_array(key, value)
  File "/usr/local/lib/python3.11/site-packages/pandas/core/frame.py", line 4008, in _setitem_array
    check_key_length(self.columns, key, value)
  File "/usr/local/lib/python3.11/site-packages/pandas/core/indexers/utils.py", line 401, in check_key_length
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key`, size: 1259 (max: 255)
```

**Comment by rannick** [comment]
Ok, so I cannot reproduce the error, would it be ok to send me your files, or at least a summary of the content of each of them? I am talking about: 
- C469T-23EH16313-0-RUBAN-LIG1H.FusionInspector.fusions.abridged.tsv.annotated.coding_effect 
- C469T-23EH16313-0-RUBAN-LIG1H_fusionreport_index.html 
- C469T-23EH16313-0-RUBAN-LIG1H.tsv 
- C469T-23EH16313-0-RUBAN-LIG1H.fusions.csv

**Comment by vwucher** [comment]
Hi again,

Normally it is ok to share these processed RNA-seq data. I put the four files changing their name ([sample1.zip](https://github.com/nf-core/rnafusion/files/14113196/sample1.zip)).

Thanks again for your help,
Valentin
