### ISSUE TITLE
Fusioninspector issue - strand GstrandBit problem

### ISSUE THREAD

**Issue by APL-MolecularPathology** [nf-core/rnafusion#487]
### Description of the bug

When nextflow attempts to execute the fusioninspector command, there is a fatal error:

EXITING because of FATAL ERROR: cannot insert sequence on the fly because of strand GstrandBit problem
SOLUTION: please contact STAR author at https://groups.google.com/forum/#!forum/rna-star

The solution that is recommended is to add the parameter: --limitSjdbInsertNsj 10000000 to the fusioninspector command. 

I have done this by adding the following param to my nextflow command: 

 --fusioninspector_limitSjdbInsertNsj 10000000

However, I still get the same error.

In the error message I noticed the following: 

Command executed:

  FusionInspector \
      --fusions 23_0363-L-RNA.fusionreport.tsv \
      --genome_lib ctat_genome_lib_build_dir \
      --left_fq 23_0363-L-RNA_S11_R1_001.fastq.gz --right_fq 23_0363-L-RNA_S11_R2_001.fastq.gz \
      --CPU 12 \
      -O . \
      --out_prefix 23_0363-L-RNA \
      --vis --STAR_xtra_params "--limitSjdbInsertNsj 10000000" --annotate --examine_coding_effect

Due to the fact that the --limitSJdbInsertNsj 10000000 param is in quotations, is the fusioninspector command ignoring this parameter? Is that why I continue to get the same error message?

### Command used and terminal output

```console
nextflow command: 

/data/nextflow/nextflow run nf-core/rnafusion \
	-profile singularity \
	--stringtie \ 
	--arriba \
	--starfusion \
	--stringtie \
	--fusionreport \
	--input /apps/Run_data/Illumina_NextSeq/nf_core_sample_sheets/230519_VH01371_12_AACKHWNM5_sample_sheet.csv \
 	--genomes_base /data/rnafusion_ref \  
	--outdir /apps/archive_Molpath/NGS_ClinicalRuns/South_Fusion_Illumina/NF_Core_RNAFUSION/GRCh38_test_no_fusioncatcher \
	--email ******* \ 
	--cosmic_username ******** \ 
	--cosmic_passwd ******** \ 
	--starfusion_ref /data/STAR/GRCh38_gencode_v22_CTAT_lib_Mar012021.STAR_v2.7.11a.plug-n-play/ctat_genome_lib_build_dir \ 
	--fusioninspector_limitSjdbInsertNsj 10000000 \ 
	--fasta /data/STAR/GRCh38_gencode_v22_CTAT_lib_Mar012021.STAR_v2.7.11a.plug-n-play/ctat_genome_lib_build_dir/ref_genome.fa \ 
	--fai /data/STAR/GRCh38_gencode_v22_CTAT_lib_Mar012021.STAR_v2.7.11a.plug-n-play/ctat_genome_lib_build_dir/ref_genome.fa.fai \ 
	-resume

Terminal Output: 

ERROR ~ Error executing process > 'NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:FUSIONINSPECTOR (23_0363-L-RNA)'

Caused by:
  Process `NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:FUSIONINSPECTOR (23_0363-L-RNA)` terminated with an error exit status (1)

Command executed:

  FusionInspector \
      --fusions 23_0363-L-RNA.fusionreport.tsv \
      --genome_lib ctat_genome_lib_build_dir \
      --left_fq 23_0363-L-RNA_S11_R1_001.fastq.gz --right_fq 23_0363-L-RNA_S11_R2_001.fastq.gz \
      --CPU 12 \
      -O . \
      --out_prefix 23_0363-L-RNA \
      --vis --STAR_xtra_params "--limitSjdbInsertNsj 10000000" --annotate --examine_coding_effect

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:FUSIONINSPECTOR":
      STAR-Fusion: $(STAR-Fusion --version 2>&1 | grep -i 'version' | sed 's/STAR-Fusion version: //')
  END_VERSIONS

Command exit status:
  1

Command output:
  Running: cp 23_0363-L-RNA.fa fi_workdir/23_0363-L-RNA.fa
  Execution Time = 0.00 minutes. CMD: cp 23_0363-L-RNA.fa fi_workdir/23_0363-L-RNA.fa
  Running: touch chckpts_dir/cp_contigs_file_workdir
  Running: cp 23_0363-L-RNA.gtf fi_workdir/23_0363-L-RNA.gtf
  Execution Time = 0.00 minutes. CMD: cp 23_0363-L-RNA.gtf fi_workdir/23_0363-L-RNA.gtf
  Running: touch chckpts_dir/cp_gtf_file_workdir.ok
  Running: /usr/local/src/STAR-Fusion/FusionInspector/util/fasta_and_gtf_to_cytoband.pl 23_0363-L-RNA.fa 23_0363-L-RNA.gtf > cytoBand.txt
  Execution Time = 0.00 minutes. CMD: /usr/local/src/STAR-Fusion/FusionInspector/util/fasta_and_gtf_to_cytoband.pl 23_0363-L-RNA.fa 23_0363-L-RNA.gtf > cytoBand.txt
  Running: touch chckpts_dir/cytoband.ok
  Running: /usr/local/src/STAR-Fusion/FusionInspector/util/gtf_gene_to_bed.pl 23_0363-L-RNA.gtf > 23_0363-L-RNA.bed
  Execution Time = 0.00 minutes. CMD: /usr/local/src/STAR-Fusion/FusionInspector/util/gtf_gene_to_bed.pl 23_0363-L-RNA.gtf > 23_0363-L-RNA.bed
  Running: touch chckpts_dir/merged_contig_gtf_to_bed.ok
  Running: sort -k1,1 -k2,2n 23_0363-L-RNA.bed > 23_0363-L-RNA.bed.sorted.bed
  Execution Time = 0.00 minutes. CMD: sort -k1,1 -k2,2n 23_0363-L-RNA.bed > 23_0363-L-RNA.bed.sorted.bed
  Running: touch chckpts_dir/23_0363-L-RNA.bed.bedsort.ok
  Running: bgzip -f 23_0363-L-RNA.bed.sorted.bed
  Execution Time = 0.00 minutes. CMD: bgzip -f 23_0363-L-RNA.bed.sorted.bed
  Running: touch chckpts_dir/23_0363-L-RNA.bed.bgzip.ok
  Running: tabix -p bed 23_0363-L-RNA.bed.sorted.bed.gz
  Execution Time = 0.00 minutes. CMD: tabix -p bed 23_0363-L-RNA.bed.sorted.bed.gz
  Running: touch chckpts_dir/23_0363-L-RNA.bed.tabix.ok
  Running: samtools faidx 23_0363-L-RNA.fa
  Execution Time = 0.00 minutes. CMD: samtools faidx 23_0363-L-RNA.fa
  Running: touch chckpts_dir/merged_contig_fai.ok
  Running: /usr/local/src/STAR-Fusion/FusionInspector/util/run_FI_STAR.pl --genome ctat_genome_lib_build_dir/ref_genome.fa --patch fi_workdir/23_0363-L-RNA.fa --max_mate_di
  Execution Time = 0.00 minutes. CMD: /usr/local/src/STAR-Fusion/FusionInspector/util/fasta_and_gtf_to_cytoband.pl 23_0363-L-RNA.fa 23_0363-L-RNA.gtf > cytoBand.txt
  Running: touch chckpts_dir/cytoband.ok
  Running: /usr/local/src/STAR-Fusion/FusionInspector/util/gtf_gene_to_bed.pl 23_0363-L-RNA.gtf > 23_0363-L-RNA.bed
  Execution Time = 0.00 minutes. CMD: /usr/local/src/STAR-Fusion/FusionInspector/util/gtf_gene_to_bed.pl 23_0363-L-RNA.gtf > 23_0363-L-RNA.bed
  Running: touch chckpts_dir/merged_contig_gtf_to_bed.ok
  Running: sort -k1,1 -k2,2n 23_0363-L-RNA.bed > 23_0363-L-RNA.bed.sorted.bed
  Execution Time = 0.00 minutes. CMD: sort -k1,1 -k2,2n 23_0363-L-RNA.bed > 23_0363-L-RNA.bed.sorted.bed
  Running: touch chckpts_dir/23_0363-L-RNA.bed.bedsort.ok
  Running: bgzip -f 23_0363-L-RNA.bed.sorted.bed
  Execution Time = 0.00 minutes. CMD: bgzip -f 23_0363-L-RNA.bed.sorted.bed
  Running: touch chckpts_dir/23_0363-L-RNA.bed.bgzip.ok
  Running: tabix -p bed 23_0363-L-RNA.bed.sorted.bed.gz
  Execution Time = 0.00 minutes. CMD: tabix -p bed 23_0363-L-RNA.bed.sorted.bed.gz
  Running: touch chckpts_dir/23_0363-L-RNA.bed.tabix.ok
  Running: samtools faidx 23_0363-L-RNA.fa
  Execution Time = 0.00 minutes. CMD: samtools faidx 23_0363-L-RNA.fa
  Running: touch chckpts_dir/merged_contig_fai.ok
  Running: /usr/local/src/STAR-Fusion/FusionInspector/util/run_FI_STAR.pl --genome ctat_genome_lib_build_dir/ref_genome.fa --patch fi_workdir/23_0363-L-RNA.fa --max_mate_di_0363-L-RNA_S11_R1_001.fastq.gz 23_0363-L-RNA_S11_R2_001.fastq.gz" --STAR_xtra_params "--limitSjdbInsertNsj 10000000"
  May 16 11:29:43 ..... started STAR run
  May 16 11:29:43 ..... loading genome
  Error: Command '/usr/local/src/STAR-Fusion/FusionInspector/util/run_FI_STAR.pl --genome ctat_genome_lib_build_dir/ref_genome.fa --patch fi_workdir/23_0363-L-RNA.fa --max_ads "23_0363-L-RNA_S11_R1_001.fastq.gz 23_0363-L-RNA_S11_R2_001.fastq.gz" --STAR_xtra_params "--limitSjdbInsertNsj 10000000" ' returned non-zero exit status 2., exit val: 2
  Error, command: [ /usr/local/src/STAR-Fusion/FusionInspector/util/run_FI_STAR.pl --genome ctat_genome_lib_build_dir/ref_genome.fa --patch fi_workdir/23_0363-L-RNA.fa --mareads "23_0363-L-RNA_S11_R1_001.fastq.gz 23_0363-L-RNA_S11_R2_001.fastq.gz" --STAR_xtra_params "--limitSjdbInsertNsj 10000000"  ] failed, stack trace: [ st: file:/usr/local
  st: file:/usr/local/src/STAR-Fusion/FusionInspector/FusionInspector, lineno:788
  st: file:/usr/local/src/STAR-Fusion/FusionInspector/FusionInspector, lineno:1942
   ]

Command error:
  Execution Time = 0.00 minutes. CMD: cp 23_0363-L-RNA.gtf fi_workdir/23_0363-L-RNA.gtf
  Running: touch chckpts_dir/cp_gtf_file_workdir.ok
  Running: /usr/local/src/STAR-Fusion/FusionInspector/util/fasta_and_gtf_to_cytoband.pl 23_0363-L-RNA.fa 23_0363-L-RNA.gtf > cytoBand.txt
  Execution Time = 0.00 minutes. CMD: /usr/local/src/STAR-Fusion/FusionInspector/util/fasta_and_gtf_to_cytoband.pl 23_0363-L-RNA.fa 23_0363-L-RNA.gtf > cytoBand.txt
  Running: touch chckpts_dir/cytoband.ok
  Running: /usr/local/src/STAR-Fusion/FusionInspector/util/gtf_gene_to_bed.pl 23_0363-L-RNA.gtf > 23_0363-L-RNA.bed
  -parsing GTF file: 23_0363-L-RNA.gtf
  Execution Time = 0.00 minutes. CMD: /usr/local/src/STAR-Fusion/FusionInspector/util/gtf_gene_to_bed.pl 23_0363-L-RNA.gtf > 23_0363-L-RNA.bed
  Running: touch chckpts_dir/merged_contig_gtf_to_bed.ok
  Running: sort -k1,1 -k2,2n 23_0363-L-RNA.bed > 23_0363-L-RNA.bed.sorted.bed
  Execution Time = 0.00 minutes. CMD: sort -k1,1 -k2,2n 23_0363-L-RNA.bed > 23_0363-L-RNA.bed.sorted.bed
  Running: touch chckpts_dir/23_0363-L-RNA.bed.bedsort.ok
  Running: bgzip -f 23_0363-L-RNA.bed.sorted.bed
  Execution Time = 0.00 minutes. CMD: bgzip -f 23_0363-L-RNA.bed.sorted.bed
  Running: touch chckpts_dir/23_0363-L-RNA.bed.bgzip.ok
  Running: tabix -p bed 23_0363-L-RNA.bed.sorted.bed.gz
  Execution Time = 0.00 minutes. CMD: tabix -p bed 23_0363-L-RNA.bed.sorted.bed.gz
  Running: touch chckpts_dir/23_0363-L-RNA.bed.tabix.ok
  Running: samtools faidx 23_0363-L-RNA.fa
  Execution Time = 0.00 minutes. CMD: samtools faidx 23_0363-L-RNA.fa
  Running: touch chckpts_dir/merged_contig_fai.ok
  Running: /usr/local/src/STAR-Fusion/FusionInspector/util/run_FI_STAR.pl --genome ctat_genome_lib_build_dir/ref_genome.fa --patch fi_workdir/23_0363-L-RNA.fa --max_mate_di_0363-L-RNA_S11_R1_001.fastq.gz 23_0363-L-RNA_S11_R2_001.fastq.gz" --STAR_xtra_params "--limitSjdbInsertNsj 10000000"
  * Running CMD: /usr/local/bin/STAR  --runThreadN 12  --genomeDir ctat_genome_lib_build_dir/ref_genome.fa.star.idx  --outSAMtype BAM SortedByCoordinate  --twopassMode Noneht   --alignMatesGapMax 100000  --alignIntronMax 100000  --outSAMattributes All  --readFilesIn 23_0363-L-RNA_S11_R1_001.fastq.gz 23_0363-L-RNA_S11_R2_001.fastq.gz  --genomeNA.gtf  --alignSJstitchMismatchNmax 5 -1 5 5  --scoreGapNoncan -6  --readFilesCommand 'gunzip -c'  --limitSjdbInsertNsj 10000000
  May 16 11:29:43 ..... started STAR run
  May 16 11:29:43 ..... loading genome

  EXITING because of FATAL ERROR: cannot insert sequence on the fly because of strand GstrandBit problem
  SOLUTION: please contact STAR author at https://groups.google.com/forum/#!forum/rna-star

  May 16 11:29:58 ...... FATAL ERROR, exiting
  Error, cmd: /usr/local/bin/STAR  --runThreadN 12  --genomeDir ctat_genome_lib_build_dir/ref_genome.fa.star.idx  --outSAMtype BAM SortedByCoordinate  --twopassMode None  -  --alignMatesGapMax 100000  --alignIntronMax 100000  --outSAMattributes All  --readFilesIn 23_0363-L-RNA_S11_R1_001.fastq.gz 23_0363-L-RNA_S11_R2_001.fastq.gz  --genomeFasgtf  --alignSJstitchMismatchNmax 5 -1 5 5  --scoreGapNoncan -6  --readFilesCommand 'gunzip -c'  --limitSjdbInsertNsj 10000000  died with ret 26880 No such file or directory
        Pipeliner::run(Pipeliner=HASH(0x561baf483578)) called at /usr/local/src/STAR-Fusion/FusionInspector/util/run_FI_STAR.pl line 322
  Error: Command '/usr/local/src/STAR-Fusion/FusionInspector/util/run_FI_STAR.pl --genome ctat_genome_lib_build_dir/ref_genome.fa --patch fi_workdir/23_0363-L-RNA.fa --max_ads "23_0363-L-RNA_S11_R1_001.fastq.gz 23_0363-L-RNA_S11_R2_001.fastq.gz" --STAR_xtra_params "--limitSjdbInsertNsj 10000000" ' returned non-zero exit status 2., exit val: 2
  Error, command: [ /usr/local/src/STAR-Fusion/FusionInspector/util/run_FI_STAR.pl --genome ctat_genome_lib_build_dir/ref_genome.fa --patch fi_workdir/23_0363-L-RNA.fa --mareads "23_0363-L-RNA_S11_R1_001.fastq.gz 23_0363-L-RNA_S11_R2_001.fastq.gz" --STAR_xtra_params "--limitSjdbInsertNsj 10000000"  ] failed, stack trace: [ st: file:/usr/local
  st: file:/usr/local/src/STAR-Fusion/FusionInspector/FusionInspector, lineno:788
  st: file:/usr/local/src/STAR-Fusion/FusionInspector/FusionInspector, lineno:1942
   ]
  Traceback (most recent call last):
    File "/usr/local/src/STAR-Fusion/FusionInspector/FusionInspector", line 1942, in <module>
      FusionInspector().run()
    File "/usr/local/src/STAR-Fusion/FusionInspector/FusionInspector", line 1516, in run
      pipeliner.run()
    File "/usr/local/src/STAR-Fusion/FusionInspector/PyLib/Pipeliner.py", line 71, in run
      cmd.run(checkpoint_dir)
    File "/usr/local/src/STAR-Fusion/FusionInspector/PyLib/Pipeliner.py", line 132, in run
      raise RuntimeError(errmsg)
  RuntimeError: Error, command: [ /usr/local/src/STAR-Fusion/FusionInspector/util/run_FI_STAR.pl --genome ctat_genome_lib_build_dir/ref_genome.fa --patch fi_workdir/23_0363 fi_workdir --reads "23_0363-L-RNA_S11_R1_001.fastq.gz 23_0363-L-RNA_S11_R2_001.fastq.gz" --STAR_xtra_params "--limitSjdbInsertNsj 10000000"  ] failed, stack trace: [ st: f
  st: file:/usr/local/src/STAR-Fusion/FusionInspector/FusionInspector, lineno:788
  st: file:/usr/local/src/STAR-Fusion/FusionInspector/FusionInspector, lineno:1942
   ]

Work dir:
  /data/nextflow/work/4e/5ced79f866dce39f50e0d5aec56603

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
ERROR ~ Failed to invoke `workflow.onComplete` event handler

 -- Check script '/home/********/.nextflow/assets/nf-core/rnafusion/./workflows/build_references.nf' at line: 91 or see '.nextflow.log' file for more details
```

### System information

N E X T F L O W  ~  version 23.10.1
Hardware: virtual machine, RHEL 8.9, 12 CPU, 96 GB RAM, 500 GB HD
Executor: local with sudo privileges
Container engine: singularity
OS: RHEL 8.9
version of nf-core/rnafusion:  nf-core/rnafusion v3.0.1-g98f02be

**Comment by rannick** [comment]
See fusioninspector directly and use parameter fusioncatcher_limitSjdbInsertNsj if necessary
