### ISSUE TITLE
Error, no fusion contigs written at /usr/local/src/STAR-Fusion/FusionInspector/util/fusion_pair_to_mini_genome_join.pl

### ISSUE THREAD

**Issue by HCLbioinfo** [nf-core/rnafusion#489]
### Description of the bug

In a sequencing run with multiple samples, `NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:FUSIONINSPECTOR` fails for one sample because there seems to be no pertinent fusion to report :

`cat RNA1559-1.fusionreport.tsv`
```
VEZF1--VEZF1
```

### Command used and terminal output

```console
nextflow-23.10.1-all run
	-work-dir .../work
	-ansi-log false nf-core/rnafusion
	-r 3.0.2
	-c HCL.conf
	-c SLURM.conf
	-profile singularity
	--input samplesheet.csv
	--outdir output
	--genomes_base .../references
	--arriba
	--read_length 150
	--fastp_trim
	-resume
```

```
ERROR ~ Error executing process > 'NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:FUSIONINSPECTOR (RNA1559-1)'

Caused by:
  Process `NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:FUSIONINSPECTOR (RNA1559-1)` terminated with an error exit status (1)

Command executed:

  FusionInspector \
      --fusions RNA1559-1.fusionreport.tsv \
      --genome_lib ctat_genome_lib_build_dir \
      --left_fq RNA1559-1_1.fastp.fastq.gz --right_fq RNA1559-1_2.fastp.fastq.gz \
      --CPU 12 \
      -O . \
      --out_prefix RNA1559-1 \
      --vis  --annotate --examine_coding_effect
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:FUSIONINSPECTOR":
      STAR-Fusion: $(STAR-Fusion --version 2>&1 | grep -i 'version' | sed 's/STAR-Fusion version: //')
  END_VERSIONS

Command exit status:
  1

Command output:
  Running: /usr/local/src/STAR-Fusion/FusionInspector/util/fusion_pair_to_mini_genome_join.pl --fusions RNA1559-1.fusionreport.tsv --gtf ctat_genome_lib_build_dir/ref_annot.gtf --genome_fa ctat_genome_lib_build_dir/ref_genome.fa --out_prefix RNA1559-1 --shrink_introns --max_intron_length 1000 
  Error: Command '/usr/local/src/STAR-Fusion/FusionInspector/util/fusion_pair_to_mini_genome_join.pl --fusions RNA1559-1.fusionreport.tsv --gtf ctat_genome_lib_build_dir/ref_annot.gtf --genome_fa ctat_genome_lib_build_dir/ref_genome.fa --out_prefix RNA1559-1 --shrink_introns --max_intron_length 1000 ' returned non-zero exit status 25., exit val: 25
  Error, command: [ /usr/local/src/STAR-Fusion/FusionInspector/util/fusion_pair_to_mini_genome_join.pl --fusions RNA1559-1.fusionreport.tsv --gtf ctat_genome_lib_build_dir/ref_annot.gtf --genome_fa ctat_genome_lib_build_dir/ref_genome.fa --out_prefix RNA1559-1 --shrink_introns --max_intron_length 1000  ] failed, stack trace: [ st: file:/usr/local/src/STAR-Fusion/FusionInspector/PyLib/Pipeliner.py, lineno:86
  st: file:/usr/local/src/STAR-Fusion/FusionInspector/FusionInspector, lineno:654
  st: file:/usr/local/src/STAR-Fusion/FusionInspector/FusionInspector, lineno:1942
   ] 

Command error:
  Done.
  Error, no fusion contigs written at /usr/local/src/STAR-Fusion/FusionInspector/util/fusion_pair_to_mini_genome_join.pl line 251.
  Traceback (most recent call last):
    File "/usr/local/src/STAR-Fusion/FusionInspector/FusionInspector", line 1942, in <module>
      FusionInspector().run()
    File "/usr/local/src/STAR-Fusion/FusionInspector/FusionInspector", line 1516, in run
      pipeliner.run()
    File "/usr/local/src/STAR-Fusion/FusionInspector/PyLib/Pipeliner.py", line 71, in run
      cmd.run(checkpoint_dir)
    File "/usr/local/src/STAR-Fusion/FusionInspector/PyLib/Pipeliner.py", line 132, in run
      raise RuntimeError(errmsg)
  RuntimeError: Error, command: [ /usr/local/src/STAR-Fusion/FusionInspector/util/fusion_pair_to_mini_genome_join.pl --fusions RNA1559-1.fusionreport.tsv --gtf ctat_genome_lib_build_dir/ref_annot.gtf --genome_fa ctat_genome_lib_build_dir/ref_genome.fa --out_prefix RNA1559-1 --shrink_introns --max_intron_length 1000  ] failed, stack trace: [ st: file:/usr/local/src/STAR-Fusion/FusionInspector/PyLib/Pipeliner.py, lineno:86
  st: file:/usr/local/src/STAR-Fusion/FusionInspector/FusionInspector, lineno:654
  st: file:/usr/local/src/STAR-Fusion/FusionInspector/FusionInspector, lineno:1942
   ] 

Work dir:
  /srv/scratch/SLURM/3015/work/75/97c23809616c0bd67b7c1deeca8b27

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

### System information

- nextflow-23.10.1-all
- SLURM executor on HPC server
- Singularity container
- Debian 12
- nf-core/rnafusion 3.0.2

**Comment by rannick** [comment]
This is an issue that we have never encountered with our samples. I am reluctant to build a work around to remove the error because to me it seems that such an error needs to trigger an investigation of what is going on with the sample. You can try to run fusioncatcher/STAR-fusion as well for this sample and it will probably increase the number of fusions that fusioninspector will investigate, decreasing the likelyhood of this error. Feel free to reopen is you think something else is necessary
