### ISSUE TITLE
Summary report parameters have `input.X`

### ISSUE THREAD

**Issue by matq007** [nf-core/rnafusion#68]
The fusion-report will not work correctly when not all tools are specified. Nextflow will create an empty symlink and provide it as an input to the process. This will break the pipeline because the fusion-report doesn't check if the file is empty only if it exists.

```bash
ERROR ~ Error executing process > 'summary (QUK17111CT_tumor)'

Caused by:
  Process `summary (QUK17111CT_tumor)` terminated with an error exit status (1)

Command executed:

  fusion_report run QUK17111CT_tumor . /sfs/7/workspace/ws/iiipe01-test-rnafusion-0/dbs_for_fusion \
      --ericscript fusions.results.filtered.tsv \
      --starfusion star-fusion.fusion_predictions.tsv \
      --fusioncatcher input.3 \
      --squid input.7 \
      --pizzly pizzly_fusions.txt

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/opt/conda/envs/nf-core-rnafusion-1.0.1/bin/fusion_report", line 414, in <module>
      main()
    File "/opt/conda/envs/nf-core-rnafusion-1.0.1/bin/fusion_report", line 407, in main
      generate_report(params)
    File "/opt/conda/envs/nf-core-rnafusion-1.0.1/bin/fusion_report", line 244, in generate_report
      parser = parse(params)
    File "/opt/conda/envs/nf-core-rnafusion-1.0.1/bin/fusion_report", line 30, in parse
      tools.parse(tool, params.__dict__[tool])
    File "/opt/conda/envs/nf-core-rnafusion-1.0.1/lib/python3.6/site-packages/fusion_report/lib/tool_parser.py", line 27, in parse
      next(in_file) # skip header
  StopIteration

Work dir:
  /sfs/7/workspace/ws/iiipe01-test-rnafusion-0/work/e5/7fc73021d1d582d2625b0491c5cc82

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
Execution cancelled -- Finishing pending tasks before exit

[remote detached from 2623.testFusionReporter]
```

**Comment by apeltzer** [comment]
This looks fine now in my tests on `dev` 👍
